### ISSUE TITLE
Module version 0.1.3 is not available on Puppet forge

### ISSUE THREAD

**Issue by RochesterinNYC** [GoogleCloudPlatform/puppet-google-logging#3]
I see from the [CHANGELOG.md](https://github.com/GoogleCloudPlatform/puppet-google-logging/blob/master/CHANGELOG.md) that `v0.1.3` is available.

However, there's no `v0.1.3` release or `v0.1.3` available in Puppet forge (https://forge.puppet.com/google/glogging/changelog).

Could `v0.1.3` be made available in Puppet forge please?

As this version is the only one that is compatible with puppetlabs-apt v6+, it'd be really useful.

**Comment by RochesterinNYC** [comment]
@nelsonjr @rambleraptor @ndmckinley for visibility

**Comment by rambleraptor** [comment]
Thanks a lot for the issue! I've gone ahead and pushed the `v0.1.3` release up to Forge.

**Comment by RochesterinNYC** [comment]
Thanks!
